### PR TITLE
Removed references to SS-test user account being created by default an…

### PR DESCRIPTION
**Pull request by currmie**
…d updated install instructions

### CODE REVIEW

**Comment by currmie** [comment]
Related to:
https://github.com/artefactual/archivematica-storage-service/issues/286
https://github.com/artefactual/archivematica-docs/issues/185

**Review by sromkey — APPROVED** [review]
This all looks good to me but I did add Justin as a reviewer because I know he's also been looking at install docs lately and might catch something that I didn't.

**Comment by sromkey** [comment]
@petervg could you review this PR as well?

**Comment by sromkey** [comment]
Connected to #185

**Comment by ablwr** [comment]
@peterVG passed this to me because I'll have a working dev env before he will

**Review by ablwr — APPROVED** [review]

**Comment by ablwr** [comment]
Works excellently and the bash script to create a new user works as well.

**Comment by ablwr** [comment]
One small thing outside of the scope of this PR but on this docs page is that the instructions for cd'ing into a directory for Ubunt 14.04 should be `cd deploy-pub/playbooks/archivematica-trusty` instead of `cd deploy-pub/playbooks/archivematica`

**Comment by ablwr** [comment]
Connected to #185

**Pull request closed without merging**
