### PR TITLE
Update translations page

### PR DESCRIPTION
**Pull request by sallain**
This change is a bit of a tidy-up to the translations page in the docs, as well
as the Language section of the dashboard config pages.

Connected to archivematica/Issues#231

### CODE REVIEW

**Comment by sevein** [comment]
> Connected to #231

Remember to use the full link otherwise it won't work.

**Comment by sallain** [comment]
@sevein *facepalm*

**Review by currmie — COMMENTED** [review]
Just one minor recommendation--
I think there are 4 instances of "click save" in the file (if you do a text search). Perhaps change those instances to "click **Save Translation**" to reflect exact wording from the Transifex UI.

**Comment by sallain** [comment]
@currmie thanks! I have incorporated that suggestion.

**Pull request merged**
