### PR TITLE
Update scaling docs for 1.11

### PR DESCRIPTION
**Pull request by cole**
Relates to: https://github.com/archivematica/Issues/issues/961, https://github.com/archivematica/Issues/issues/785

This should actually go into 1.11 once it's created.

* Consistent spelling of optimise
* Update available MCPServer options
* Include gunicorn worker options
* ~TODO: Include MySQL for SS option~ Deferring this for now, needs another issue and PR.

### CODE REVIEW

**Comment by sallain** [comment]
@cole just a note to say that the `undefined label` errors that Travis is throwing up will be resolved by other PRs (#316 and #317); once they're merged Travis should pass.

**Comment by sallain** [comment]
@cole Other PRs have been merged!

**Comment by sallain** [comment]
@cole Sorry for more messages :) Can you make sure there's an issue for this PR in [archivematica/Issues](https://github.com/archivematica/Issues/issues) with the 1.11 milestone? Then we will remember to merge this into the 1.11 docs branch when it's created.

**Comment by cole** [comment]
@sallain no worries, thanks for the updates. Yes, of course, I'll add an issue, sorry I missed that!.

**Comment by cole** [comment]
This PR is ready for review but shouldn't be merged; we'll need a new PR against `1.11`.

**Review by sallain — APPROVED** [review]

**Pull request merged**
