### PR TITLE
Review linkcheck and fix

### PR DESCRIPTION
**Pull request by sallain**
This PR looks huge but it actually just fixes a lot of broken links! Sphinx's `make linkcheck` tool suggested that about 80 links needed review across all of the documentation. A lot of the changes were minor (i.e. http instead of https) but several were legit. This is probably something we should do regularly
to ensure the health of the documentation.

I also did a little bit of the usual formatting fix-ups (i.e. line lengths, removing inline links, etc.) but no content was changed.

Note that if you run `make linkcheck` right now, you'll still see errors - mostly these are dummy links (i.e. http://10.10.10.10/), which, as Ross notes in the issue linked below, we could be filtering out by creating exclusion regex patterns for linkcheck. It's not a huge deal to review these manually, though. The other common link type that was flagged were links to GitHub docs that used an anchor - i.e. `https://github.com/artefactual/binder/tree/a2893fe589c67f147de440a52301c4025ad1cd4e#installation`. linkcheck thinks that the `#installation` anchor doesn't exist, but the link works just fine. I've elected to just ignore these.

Connected to archivematica/Issues#630

### CODE REVIEW

**Review by ross-spencer — APPROVED** [review]
Nice! :+1:

**Comment by ross-spencer** [comment]
Hi @sallain, don't forget to cherry-pick the changes into `1.10` as well when there's a chance.

**Comment by ross-spencer** [comment]
*Opens Slack and sees you're already onto it!!*

**Comment by sallain** [comment]
@ross-spencer reminder always appreciated!

**Pull request merged**
