### PR TITLE
Update vagrant instructions for 1.9

### PR DESCRIPTION
**Pull request by scollazo**
Connects to https://github.com/archivematica/Issues/issues/535

### CODE REVIEW

**Comment by scollazo** [comment]
A new Vagrant with Archivematica 1.9 has been created, and I'm uploading it to a temporary site so it can be tested

**Comment by scollazo** [comment]
The command to try the vagrant qa build of am 1.9 is:

```
mkdir vagrant-archivematica && cd vagrant-archivematica
vagrant init am19-dev http://jenkins-ci.archivematica.org/repos/vagrant/vagrant-am-dev.box
vagrant up
```

Tested/built using 
 - Ubuntu 18.04
 - Vagrant 2.1.4
 - VirtualBox 5.2.18
 - Packer 1.0.0

**Comment by scollazo** [comment]
Tested on

 - Windows 10 
 - VirtualBox 6.0.4 (latest available version )
 - Vagrant 2.2.4 ( latest available version )


The shared folder for testing with your own content works.

**Comment by mamedin** [comment]
Tested successfully on:

* macOS 10.14.2
* Vagrant 2.1.2 and virtualbox 5.2.18
* Vagrant 2.2.4 and virtualbox 6.0.4 

The shared folder for testing with your own content works.

**Comment by mamedin** [comment]
Tested successfully on:

* Debian testing (Buster)
* Vagrant 2.2.3+dfsg-1
* VirtualBox 6.0.4-dfsg-5 

The shared folder for testing with your own content works.

**Review by mamedin — APPROVED** [review]
LGTM

**Pull request merged**
