### PR TITLE
Upgrading: link to es-reindex.sh in ops-helpers

### PR DESCRIPTION
**Pull request by sevein**
es-reindex.sh is evolving as we better understand the process. To
simplify its maintenance, we're now tracking this script in the
ops-helpers repository. This commit replaces the existing notes with a
link to the [new location].

Reminder: include in 1.12 branch too.

Connects to https://github.com/archivematica/Issues/issues/1317 and https://github.com/archivematica/Issues/issues/1257.

[new location]: https://github.com/artefactual-labs/ops-helpers/tree/master/es-helpers#es-reindexsh-update-search-indices

### CODE REVIEW

**Review by currmie — APPROVED** [review]
Super helpful and great to know these tools are here for ops-troubleshooting, thank you!

```
-d "$(curl -s ${es_url}/${index} | jq '.'"${index}"' | del(.settings.index.provided_name, .settings.index.creation_date, .settings.index.uuid, .settings.index.version)')"  > /dev/null
done
```

^ Only suggestion is that the user docs could probably use a PR to update the reference to this script if not already changed.

**Comment by sevein** [comment]
Thanks! I can do that. Where do you think I should add it? Send me a link if that's easier.

**Comment by currmie** [comment]
> Thanks! I can do that. Where do you think I should add it? Send me a link if that's easier.

Sure. I was thinking the fourth code block in 'Reindex the Documents': 
[https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/#reindex-the-documents](https://www.archivematica.org/en/docs/archivematica-1.12/admin-manual/installation-setup/upgrading/upgrading/#reindex-the-documents)

**Comment by sevein** [comment]
We've discussed this offline, I'll merge now.

**Pull request merged**
