### PR TITLE
Removes dataverse admonition related to issue #269

### PR DESCRIPTION
**Pull request by sromkey**
Removes the admonition related to package extraction which is now fixed.

Connected to https://github.com/archivematica/Issues/issues/269

Will do a different PR for 1.10 branch!

### CODE REVIEW

**Comment by ablwr** [comment]
Should this now point to the 1.10 branch?

**Comment by ross-spencer** [comment]
Hi @ablwr I was trying to remember what happened to this, it was originally in 1.8 and then resolved in 1.9, and I think the admonition reduced slightly to reflect Dataverse is a WIP but this issue no longer present.

* [1.8](https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/transfer/dataverse/)
* [1.10](https://www.archivematica.org/en/docs/archivematica-1.10/user-manual/transfer/dataverse/)

So we can probably close this out.

**Comment by ablwr** [comment]
Thanks @ross-spencer! @sromkey if you agree, can you close this issue? I hope it brings you joy~

**Comment by ross-spencer** [comment]
Oh, I just saw Philip's PR... it was there all along :( 

image

Good it was caught!

**Comment by ablwr** [comment]
Oooh another one to close!!!

**Pull request closed without merging**
