### PR TITLE
sips are created from archival objects but not resources

### PR DESCRIPTION
**Pull request by eckardm**
This is (I think) a slightly less ambiguous way to describe what SIPs can be created from, based on the conversation on the [Appraisal tab Backlog pane / ArchivesSpace pane question](https://groups.google.com/forum/#!topic/archivematica/815b8wk7jR4) thread.

### CODE REVIEW

**Review by sallain — CHANGES_REQUESTED** [review]
Max, thanks for this clarification! I think it's good. One slight nitpick, can you edit so that you're truncating after 80 characters, in line with the Archivematica docs style guide? Thanks!

https://github.com/artefactual/archivematica-docs/wiki/Style-guide

**Comment by eckardm** [comment]
Should be all set!

**Review by sallain — APPROVED** [review]
Thank you!

**Comment by sromkey** [comment]
This looks good to me, thanks for the fix Max!

**Review by sromkey — APPROVED** [review]

**Comment by sallain** [comment]
Merged as 22d9ab9 and b2081d0. Thanks again, Max!

**Pull request closed without merging**
