### PR TITLE
Include reference to validatorTester.html

### PR DESCRIPTION
**Pull request by ablwr**
So nice to push directly to Github these days. :) Resolves https://github.com/archivematica/Issues/issues/244. Brief but sufficient, I think.

### CODE REVIEW

**Comment by sallain** [comment]
LGTM!

I noticed that the Travis builds failed - it looks like it's not because of a change that you made, but a bad link in archivematica-docs/admin-manual/installation-setup/installation/installation.rst at line 31. Can you check that out before you merge? Might just be a typo or something that snuck through.

**Comment by ablwr** [comment]
I think the error is unrelated to this PR, the error says "/home/travis/build/artefactual/archivematica-docs/admin-manual/installation-setup/installation/installation.rst:31:undefined label: multiple-machines (if the link has no caption the label must precede a section header)"

But in going to that file and that line, I'm not sure what it's talkin' about!

**Comment by ablwr** [comment]
I get this error locally but it does not prevent things from building. Here it is, a little fuller:

```
/home/ashley/Development/archivematica-docs/admin-manual/installation-setup/installation/installation.rst:31: WARNING: undefined label: multiple-machines (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/index.rst:207: WARNING: undefined label: fpr (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/index.rst:209: WARNING: undefined label: fpr-instruct (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/user-manual/administer/dashboard-admin.rst:289: WARNING: undefined label: digitized (if the link has no caption the label must precede a section header)
/home/ashley/Development/archivematica-docs/user-manual/ingest/ingest.rst:395: WARNING: undefined label: digitized (if the link has no caption the label must precede a section header)
```

Should I make an issue for this... erm, issue?

**Comment by ablwr** [comment]
Whats confusing me about this is that there is no multiple-machines link at installation.rst#31.

**Comment by ablwr** [comment]
Made the above issue and am gonna merge this so I can feel good about MYSELF!!!

**Pull request merged**
