### PR TITLE
uses Red Hat instead of Redhat #109

### LINKED ISSUE #109: Problem: AM17 docs use name Redhat instead of `Red Hat`
```
$ git grep -l "Redhat"
admin-manual/installation-setup/installation/install-centos.rst
admin-manual/installation-setup/installation/installation.rst
admin-manual/installation-setup/upgrading/upgrading.rst
```

### PR DESCRIPTION
**Pull request by ablwr**
Resolves #109 as well as typo in word "install." Also proof that I was successfully able to test and build locally following docs in the Wiki.

### CODE REVIEW

**Comment by ablwr** [comment]
Ah, whoops, re-building!

**Comment by sevein** [comment]
Thank you! I suggest to merge #108 before because it moves things around a bit and it would be hard for @sallain  to rebase and deal with conflicts otherwise.

**Comment by ablwr** [comment]
Ah! And this was really a trivial change so I can always re-do later. This was mostly me testing the building/changing workflow. ;)

**Comment by sallain** [comment]
I'm just going to make this change as part of the overall edits to #108, if that's okay! That way @ashley won't have to rebase :)

**Comment by ablwr** [comment]
Word!!

**Pull request closed without merging**
