### PR TITLE
replace drown-down with drop-down

### PR DESCRIPTION
**Pull request by ablwr**
Dark, @sallain, dark... 👻

### CODE REVIEW

**Review by sallain — APPROVED** [review]

**Comment by ablwr** [comment]
@sallain What causes @qubot to close this?

**Comment by jhsimpson** [comment]
Qubot is the GitHub user that is used to push changes from
gitolite.artefactual.com to GitHub.  The repos hosted at
gitolite.artefactual.com are the 'master' repos, and they are where
Artefactual staff push commits.  Qubot then pushes them to GitHub and when
GitHub detects that a PR has been merged, it marks the PR as closed, using
the name of the logged in user.

We have talked at Artefactual about changing this workflow, so that GitHub
becomes the 'master' and committers would push to GitHub instead of
gitolite.  Then PR's would be closed by the person actually merging things
instead of qubot.

I hope that can happen after the 1.7 release.

**Comment by ablwr** [comment]
Ahhh, so someone from Artefactual makes the patch there and then qubot closes it here. Got it! To the average user, it appears like a negation. I can edit the wiki just to note qubot's job in a succinct way, understanding this may change in the future.

**Comment by ablwr** [comment]
I made the change because I have the power but @sallain please adjust if necessary! https://github.com/artefactual/archivematica-docs/wiki/Contributing-guide-for-community-members

**Pull request closed without merging**
