### PR TITLE
Fixed documentation typo for REQUESTS_CA_BUNDLE.

### PR DESCRIPTION
**Pull request by R-Khera**
This is a PR to fix (partially) archivematica/Issues#432

### CODE REVIEW

**Comment by ablwr** [comment]
Thanks @R-Khera! The checks aren't passing here because you need to rebase your branch to update against some recent changes. Could you do that, and then we will be happy to merge your fix?

We have some guidelines [here](https://github.com/artefactual/archivematica-docs/wiki/Technical-details) in case you need them.

**Comment by R-Khera** [comment]
> Thanks @R-Khera! The checks aren't passing here because you need to rebase your branch to update against some recent changes. Could you do that, and then we will be happy to merge your fix?
> 
> We have some guidelines [here](https://github.com/artefactual/archivematica-docs/wiki/Technical-details) in case you need them.

Thanks for the info. I've tried to rebase it and I get the same failure message - following the guidelines allows me to repeat the test locally.

I also get the same failure message when I try running the sphinx-build on the base 1.8 branch (without any of my changes), so I'm not sure what to try next.

**Comment by sallain** [comment]
Hi @R-Khera, this is my fault! I deleted a page in storage-service-docs but forgot to delete a cross-reference to it in archivematica-docs. I've made those changes now. Please try rebasing again!

Sorry about this!

**Review by sallain — APPROVED** [review]
Thanks so much @R-Khera!

**Pull request merged**
