### PR TITLE
Updated Elasticsearch maintenance page for v. 1.6

### PR DESCRIPTION
**Pull request by jrwdunham**
I have updated the maintenance doc page so that it works with AM v. 1.6. In doing so, the following issues were noted:

1. The AM devtool `am rebuild-elasticsearch-transfer-index-from-files` no longer works. I get `ImportError: No module named databaseInterface`. The current inability to rebuild the transfer ES index is stated explicitly in this doc.

2. The query `pyes.TermQuery("mets.ns0:mets_dict_list.ns0:amdSec_dict_list.@ID", "amdsec_1")` seems like not a very good example because every AIP with at least one file will match that query. Can someone suggest a better query example?

### CODE REVIEW

**Comment by Hwesta** [comment]
Is this still accurate? Since artefactual/archivematica#138 (pre 1.4?) we have used the official Python elasticsearch library.

**Comment by jhsimpson** [comment]
@Hwesta is right, this PR needsd to be updated to remove the references to pyes, and refer to the official elasticsearch python library https://pypi.python.org/pypi/elasticsearch/1.9.0

Archivematica no longer installs pyes, so these instructions probably won't work as is.

**Review by sevein — CHANGES_REQUESTED** [review]
See comments above.

**Comment by kellyannewithane** [comment]
Fixes #37

**Comment by sallain** [comment]
@sevein Can we close this PR? Is there work here we can re-use?

**Comment by sevein** [comment]
Highly inaccurate! I'd suggest to close, but you may also want to file a new issue to capture the fact that https://www.archivematica.org/en/docs/archivematica-1.8/admin-manual/maintenance/maintenance/#elasticsearch is outdated!

**Comment by sallain** [comment]
Closed in favour of a new issue: https://github.com/archivematica/Issues/issues/292

**Pull request closed without merging**
