### PR TITLE
note raw format specification

### PR DESCRIPTION
**Pull request by ablwr**
Considered using "optimally" or "reliably" or some other softener because other formats MAY be possible, especially if user is willing to modify and customize their FPR, but "out of the box" only RAW will work reliably. Suggestions?

### CODE REVIEW

**Review by sallain — APPROVED** [review]

**Comment by sallain** [comment]
Because this section is intended to be step-by-step instructions on basic forensic procedures, I'd leave the ambiguity out. Maybe in the FPR docs there is somewhere that you could describe modifying commands for disk images - if so, that would be a good thing to hyperlink from the forensics page.

**Comment by ablwr** [comment]
I thought this was merged in but I don't see it, did it get lost?

**Comment by sallain** [comment]
@ablwr sorry I didn't see this earlier - I think it got lost. Want to try re-doing it for the 1.8 docs?

**Comment by ablwr** [comment]
Thanks, I will! This is importantttttt

**Comment by ablwr** [comment]
I need to do a little more than just recreate this because I think it could be clearer, but I will keep this on my list of things to do.

**Pull request closed without merging**
